name:  Print out secret names

# -----------------------------------------------------------------------------------
# This is a reusable workflow which implements the standard 84.51ยบ process for
# building, testing, packaging, and publishing Java Jars using the Maven
# build system.
#
# Read more about how to use it here: java-build-and-publish-README.md
#

on:
  workflow_call:
  workflow_dispatch:
jobs:
  print-stuff:
    name: Print Stuff
    runs-on: ubuntu-latest
    steps:
      - name: For Real Print Stuff
        run: |
          echo yo yo yo
          v=`(echo $ALLMYSECRETS | jq -r 'to_entries | .[] | (.key + "=" + .value)')`
          while IFS= read -r line ; do eval "echo $line >> $GITHUB_ENV" ; done <<< "$v"
          echo ENV
          env
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJson(secrets) }}
