name:  Print out secret names

# -----------------------------------------------------------------------------------
# This is a reusable workflow which implements the standard 84.51ยบ process for
# building, testing, packaging, and publishing Java Jars using the Maven
# build system.
#
# Read more about how to use it here: java-build-and-publish-README.md
#

on:
  workflow_call:
jobs:
  print-stuff:
    name: Print Stuff
    runs-on:
    steps:
      - name: For Real Print Stuff
      run: |
        echo yo yo yo
        echo "$ALLMYSECRETS"
        echo "$ALLMYVARS"
      shell: bash
      env:
        ALLMYSECRETS: ${{ toJSON(secrets) }}
        ALLMYVARS: ${{ toJSON(vars) }}